name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build the project, run all tests
        run: |
          dotnet build
          dotnet test

      - name: Generate package
        env:
          CI: false
        run: |
          dotnet pack -c Release -o out

      - name: Push nuget
        run: |
          dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate