on:
  pull_request:
    branches:
      - main

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the project, run all tests
        run: |
          dotnet build
          dotnet test